#!/bin/bash
# This file expects your answer keys to be stored in key1.sql, ..., keyn.sql. 
# This file is used in run_autograder to generate output that will be checked
# against the student's queries output. 
# THIS SCRIPT EXPECTS TO BE RUN FROM THE ./source DIRECTORY.
# 
# 2021-Update. running this file will not change the database

source ./set_database # We can't guarantee that the database variable is set, so we set it here.
if [ ! -f ./${DATABASE}.original ]; then 
  echo "Creating original database copy ..."
  cp -f ./${DATABASE} ./${DATABASE}.original
else
  cp -f ./${DATABASE}.original ./${DATABASE}
fi
DIRECTORY=.
keycount=`ls -lq | grep "key[0-9]*.sql" | wc -l`
for ((i=1; i<=$keycount; i++)) do
  #if you provide a setup sql script for this question run it now.
  if [ -f key${i}s.sql ]; then 
    sqlite3 -init sqliterc $DATABASE ".read key${i}s.sql"
  fi
  #key file is required!
  sqlite3 -init sqliterc $DATABASE ".read key${i}.sql" > "key${i}.txt"
  #if you provide an alternate test sql script for this question, run it now
  if [ -f test${i}.sql ]; then
    sqlite3 -init sqliterc $DATABASE ".read test${i}.sql" > "key${i}.txt"
  fi
  #if you provide a teardown sql script for this question, run it now
  if [ -f key${i}t.sql ]; then
    sqlite3 -init sqliterc $DATABASE ".read key${i}t.sql"
  fi
done
cp "./${DATABASE}.original" "./${DATABASE}"